"""Offline verification for the PipelineSettings feature.

Runs against a throwaway SQLite database (DATABASE_URL is set before any
backend import) with a fake explainer — no network or LLM calls. Covers:
GET/PUT /api/settings, the severity-ordering 400 guard, detect() reading
the anomaly threshold from the DB row, score_to_label reading the band
cutoffs from the DB row, the enable_precaching ingest gate, and lazy LLM
explanation on GET /api/incidents/{id}.

Run from the repository root::

    venv\\Scripts\\python.exe scripts\\verify_pipeline_settings.py
"""

import os
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

_TMP = tempfile.mkdtemp(prefix="threatiq_settings_")
os.environ["DATABASE_URL"] = f"sqlite:///{Path(_TMP) / 'test.db'}"

from fastapi import FastAPI  # noqa: E402
from fastapi.testclient import TestClient  # noqa: E402

from backend.api.incidents import router as incidents_router  # noqa: E402
from backend.api.settings import router as settings_router  # noqa: E402
from backend.correlation.correlator import EventCorrelator  # noqa: E402
from backend.database.db import SessionLocal, init_db  # noqa: E402
from backend.detection.anomaly_detector import AnomalyDetector  # noqa: E402
from backend.llm.explainer import ExplanationResult  # noqa: E402
from backend.pipeline import RULE_BASED_MARKER, ThreatPipeline, score_to_label  # noqa: E402
from backend.scoring.risk_scorer import RiskScorer  # noqa: E402

init_db()

app = FastAPI()
app.include_router(settings_router, prefix="/api")
app.include_router(incidents_router, prefix="/api")
client = TestClient(app)

checks = 0


def check(name: str, condition: bool) -> None:
    global checks
    assert condition, f"FAILED: {name}"
    checks += 1
    print(f"PASS {name}")


class FakeExplainer:
    """Explainer double counting calls; always returns an LLM result."""

    def __init__(self) -> None:
        self.calls = 0

    def explain(self, incident_dict, score_factors_dict, rag_results_list):
        self.calls += 1
        return ExplanationResult(
            observed_evidence="llm evidence",
            retrieved_context="llm context",
            ai_interpretation="llm interpretation",
            recommended_action="llm action",
            confidence="high",
            confidence_reason="Generated by the fake LLM.",
        )


def _raw_event(event_id: str) -> dict:
    return {
        "event_id": event_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "source_ip": "203.0.113.7",
        "destination_ip": "10.0.0.5",
        "event_type": "authentication_failure",
        "username": "admin",
        "failed_attempts": 9,
        "bytes_transferred": 900000,
        "port": 4444,
        "destination_asset": "dc-01",
        "asset_criticality": "critical",
        "protocol": "TCP",
        "raw_severity": "critical",
        "details": "meterpreter reverse shell; threat-intelligence hit",
    }


# --- Settings API -------------------------------------------------------- #
r = client.get("/api/settings")
check("GET /api/settings -> 200", r.status_code == 200)
body = r.json()
check("default anomaly_threshold == 0.5", body["anomaly_threshold"] == 0.5)
check(
    "default severity bands 80/60/40/20",
    (
        body["severity_critical_min"],
        body["severity_high_min"],
        body["severity_medium_min"],
        body["severity_low_min"],
    )
    == (80, 60, 40, 20),
)
check("default enable_precaching is True", body["enable_precaching"] is True)
check("default rag knobs 3 / 0.0", body["rag_top_k"] == 3 and body["rag_similarity_cutoff"] == 0.0)

r = client.put("/api/settings", json={"severity_high_min": 85})
check("PUT violating threshold order -> 400", r.status_code == 400)
check("400 carries a clear message", "strictly decreasing" in r.json()["detail"])

r = client.put(
    "/api/settings",
    json={"anomaly_threshold": 0.7, "rag_top_k": 5, "enable_precaching": True},
)
check(
    "PUT valid partial update -> 200 with merged values",
    r.status_code == 200
    and r.json()["anomaly_threshold"] == 0.7
    and r.json()["rag_top_k"] == 5
    and r.json()["severity_critical_min"] == 80,
)

# --- detect() default threshold comes from the DB row -------------------- #
detector = AnomalyDetector()
event = {
    "timestamp": datetime.now(timezone.utc).isoformat(),
    "attempts": 9,
    "bytes_transferred": 900000,
    "port": 4444,
    "source_ip": "203.0.113.7",
    "asset_criticality": "critical",
}
client.put("/api/settings", json={"anomaly_threshold": 0.0})
check(
    "detect() with DB threshold 0.0 flags anomaly",
    detector.detect(event)["is_anomaly"] is True,
)
client.put("/api/settings", json={"anomaly_threshold": 0.9999})
check(
    "detect() with DB threshold 0.9999 does not flag",
    detector.detect(event)["is_anomaly"] is False,
)
client.put("/api/settings", json={"anomaly_threshold": 0.5})
check(
    "fresh detect() without threshold matches explicit 0.5",
    detector.detect(event) == detector.detect(event, threshold=0.5),
)

# --- score_to_label reads band cutoffs from the DB row ------------------- #
check("score_to_label(75) == 'high' with defaults", score_to_label(75) == "high")
client.put("/api/settings", json={"severity_critical_min": 70})
check("score_to_label(75) == 'critical' after update", score_to_label(75) == "critical")
client.put("/api/settings", json={"severity_critical_min": 80})
check("score_to_label(75) == 'high' after restore", score_to_label(75) == "high")

# --- enable_precaching gate at ingest time -------------------------------- #
fake = FakeExplainer()
session = SessionLocal()
pipeline = ThreatPipeline(
    detector=detector,
    correlator=EventCorrelator(),
    scorer=RiskScorer(),
    explainer=fake,
    db=session,
)

client.put("/api/settings", json={"enable_precaching": True})
summaries = pipeline.process([_raw_event("evt-precache-on")])
check("precaching ON: explainer called at ingest", fake.calls == 1)
check(
    "precaching ON: high-score incident persisted",
    summaries and summaries[0]["total_score"] >= 60,
)

client.put("/api/settings", json={"enable_precaching": False})
summaries = pipeline.process([_raw_event("evt-precache-off")])
check("precaching OFF: no LLM call at ingest", fake.calls == 1)
lazy_id = summaries[0]["id"]

# --- lazy explanation on first detail view -------------------------------- #
app.state.explainer = fake
r = client.get(f"/api/incidents/{lazy_id}")
check("GET incident detail -> 200", r.status_code == 200)
check("precaching OFF: lazy LLM call on first view", fake.calls == 2)
explanation = r.json()["llm_explanation"]
check(
    "lazy explanation persisted (no rule-based marker)",
    explanation is not None
    and RULE_BASED_MARKER not in (explanation["confidence_reason"] or ""),
)
r = client.get(f"/api/incidents/{lazy_id}")
check("second view served from cache (no new LLM call)", fake.calls == 2)

client.put("/api/settings", json={"enable_precaching": True})
session.close()
print(f"\nAll {checks} checks passed.")
